### ISSUE TITLE
last vote counts chain delegation

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#1]
having explicit code for delegation is sorta silly; we get it for free in rholang.

https://github.com/rchain-community/community/blob/54779fd10ce3ea4e3ee32afeb85ec47b61a962f5/Ballot.rho#L130

**Comment by jimscarver** [comment]
If the person votes their vote counts but if they do not the delegates vote counts for them. At some point here should be a way to see who the delegate is and what their vote is.

**Comment by dckc** [comment]
Ok... a vote that only counts if some other vote is not cast is novel.

I wonder if the code works that way currently. I suspect the current code does last-vote-counts.

**Comment by jimscarver** [comment]
last vote counts but the chain of delegates is followed until there is a non nil vote.

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Am I correct that the demo of liquid democracy answers this and the issue should be closed?

**Comment by dckc** [comment]
yes.
