### ISSUE TITLE
rgov javascript/rest api

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#100]

**Comment by dckc** [comment]
What javascript/rest api would you want that we don't already have? How is this a ui issue?

We're using https://developer.rchain.coop/rnode-api

**Comment by Bill-Keuntje** [comment]
This issue is primarily for discussion purposes.
The proposal is to have https://developer.rchain.coop/rgov-api with appropriate functionality.
@jimscarver @w2vy

**Comment by dckc** [comment]
Every validator should support a new rest api for rgov? Is rgov special or should the core team expect such requests from every community project?

Without noting at least one specific piece of functionality, this isn't actionable. Please fix or close.

**Comment by jimscarver** [comment]
I think this was to be an api for the client side to use actions, e.g. localhost:8080/actions/peekInbox?type=issue&subtype=color

Thinking about it now I do not see much utility in this.
