### ISSUE TITLE
regression tests, ci (for double voter, ...)

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#103]
best practice when merging a bug fix such as #102 is to have a regression test and to have a continuous integration system run all the tests for each PR.

Here's hoping...

cc @jimscarver @Bill-Keuntje

**Comment by Bill-Keuntje** [comment]
> best practice when merging a bug fix such as #102 is to have a regression test and to have a continuous integration system run all the tests for each PR.
> 
> Here's hoping...
> 
> cc @jimscarver @Bill-Keuntje

Agreed.
Questions:
1) I thought rhobot was doing continuous integration testing?
2) Until the development scripts are refactored into nodejs, won't this involve more shell scripting?
3) Should we create an integration testing database that has predefined users with inboxes, etc?

**Comment by dckc** [comment]
> 1. I thought rhobot was doing continuous integration testing?

but what I'm talking about is "to have a continuous integration system run all the tests for each PR"

> 2. Until the development scripts are refactored into nodejs, won't this involve more shell scripting?

something like that, yes; here's hoping for more js than shell

> 3. Should we create an integration testing database that has predefined users with inboxes, etc?

good idea.

**Comment by Bill-Keuntje** [comment]
Creating an integration testing database should be relatively straightforward. Not being a guru on github or open-source best practices, where does it get stored? @dckc

**Comment by dckc** [comment]
Code to build the database just goes with all the other code. Maybe some of it in .csv or .json files.

The database itself goes in rnode, no?

**Comment by Bill-Keuntje** [comment]
> Code to build the database just goes with all the other code. Maybe some of it in .csv or .json files.
> 
> The database itself goes in rnode, no?

Yes, code to create such a database goes with other code. I guess what I'm asking is if we want to have one (or more?) "standard rnode testing image" stored somewhere that can simply be downloaded, OR will we be regenerating the rnode image every time we do a single regression test. Some tests could conceivably create rnode changes that would affect other tests?

**Comment by Bill-Keuntje** [comment]
@w2vy Can we use snapshots for resolving the "reusable testing image" problem?

**Comment by w2vy** [comment]
I have each of the functions for the demo script working in python
I need to write a routine to search for specific  data values in the returned json
I am thinking something like 
value = find_data(json_data, ["ExprMap", "data". "URI", "ExprUri", "data"])

**Comment by jimscarver** [comment]
> I need to write a routine to search for specific data values in the returned json
> I am thinking something like
> value = find_data(json_data, ["ExprMap", "data". "URI", "ExprUri", "data"])

I would use jq https://pypi.org/project/jq/  I use https://jqplay.org/ to debug and reference examples below

**Comment by dckc** [comment]
> I have each of the functions for the demo script working in python

nice!

Help me find it? I don't see a relevant branch at a glance.

If you haven't checked in and pushed yet, please do! Any time you have something working, especially something worth commenting on, please do commit and push, even if only to a throw-away branch.

**Comment by w2vy** [comment]
I was wanting it to be polished a bit more... done it is branch "add-pyrchain-testing" branch
test_voting.py is not tested yet, each of the individual steps have been tested...

**Comment by dckc** [comment]
Thanks!

for (my) reference: https://github.com/rchain-community/rgov/compare/add-pyrchain-testing

**Comment by w2vy** [comment]
@dckc I messed up the other branch (I tried rebasing - I will likely never try that again)
We reverted that merge and I am going to re-do it here:
https://github.com/rchain-community/rgov/tree/add-regression-testing-pyrchain
