### ISSUE TITLE
Localhost setup video

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#109]
There is no video showing how *explicitly* the steps for setting up a localhost environment.

**Comment by w2vy** [comment]
I could do that one since my machine can run bootstrap and deploy_all in about 5 mins.
Since the bootstrap builds an empty rchain, does that part apply to anyone doing development?
Like [Getting Started](https://rchain.coop/get-started.html)?

**Comment by Bill-Keuntje** [comment]
@David405 Can we close this?

**Comment by David405** [comment]
https://drive.google.com/file/d/1kEcC7OFNpeyZ33dI5M0divYW5ImXbEdR/view?usp=sharing here is the link to the demo

**Comment by David405** [comment]
https://drive.google.com/file/d/1kEcC7OFNpeyZ33dI5M0divYW5ImXbEdR/view?usp=sharing here is the link to the demo

**Comment by Bill-Keuntje** [comment]
@jimscarver where do we keep these four public consumption?

**Comment by Bill-Keuntje** [comment]
Video is complete, we just need a location for the public to access it.
