### ISSUE TITLE
prevent creation of multiple inboxes

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/rgov#115]
- [x] Create a treeHashMap of inboxes being created at bootstrap. 
 - [x] Check for existing inbox before creating another in newInbox action.
 - [x] add delete inbox action

**Comment by dckc** [comment]
resist the urge to centralize!

A list of all inboxes in the world goes against my architectural intuitions. Hm.

**Comment by jimscarver** [comment]
we could just keep an exists flag for each inbox but there is utility in having the inbox sp you could send capabilities to any rev address..

The ibox could even be created before a user joins.

**Comment by dckc** [comment]
hm. we already do register our inboxes as a matter of course -- in the RChain registry. So in some sense there's no harm in registering them in another place.

**Comment by Bill-Keuntje** [comment]
Assuming 3 inboxes per individual, that's ~24 billion inboxes for the entire world. We should make sure TreeHashMap performs to our liking at that scale.

**Comment by Bill-Keuntje** [comment]
> we could just keep an exists flag for each inbox but there is utility in having the inbox sp you could send capabilities to any rev address..
> 
> The ibox could even be created before a user joins.

I like the idea of a user not needing to create an inbox.

**Comment by dckc** [comment]
What? how is the user assured that they are the only one with access to their inbox if they do not create it?

**Comment by Bill-Keuntje** [comment]
Closed by #165 and creation of ancillary issues
