### ISSUE TITLE
Implement `rho:rchain:rgov` class

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#126]

**Comment by dckc** [comment]
What does the title mean? `rho:rchain:rgov` looks like a URI; how do I make sense of it as a class?

Secondly, why should the whole rchain community reserve `rgov` on every validator for this project? Is every project expected to get a new URI in the code that goes on all the validators?

**Comment by Bill-Keuntje** [comment]
rgov always needs a starting point -- a singleton instance to gain access to the functionality. The proposal is ```rho:rchain:rgov```
@jimscarver @w2vy

**Comment by dckc** [comment]
Adding a new rho:rchain:XYZ uri involves changing every validator and probably a hard fork. I don't see anything like sufficient motivation.

The alternative is that the master contract is a configuration setting. If someone doesn't know what uri to use, they have to generate one (and deploy all the contracts). This is the way all blockchain contract deployment works, afaik.

**Comment by Bill-Keuntje** [comment]
After considerable consultation with @tgrospic, the ```rho:rchain:rgov``` idea is untenable. We need to work on the alternative: multiple URIs, probably stored in multiple files.

**Comment by Bill-Keuntje** [comment]
Closing in lieu of #66
