### ISSUE TITLE
Community leaks write access to infoCh, inbox

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#13]
It's not used as far as I can tell.

https://github.com/rchain-community/rho-bot/blob/f532b2e636c6c6dc6d940fa0e8e0d51d5e603c77/Community.rho#L8

**Comment by dckc** [comment]
I can replace any community's inbox:

```
new ch in {
  Community!("lookup", *ch) | for (commMap <- ch) {
    match @commMap.get("community1")) {
     infoCh => for(_erase <- infoCh) { infoCh!({ "request": attackerMailbox ) }
    }
  }
}
```

https://github.com/rchain-community/liquid-democracy/blob/60d7365f2776695babc9f0304e56dac80a4e34f4/Community.rho#L76

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Does the @jimscarver current Group work (#78) obsolete this issue?

**Comment by dckc** [comment]
#78 is still open, so no, I don't think so. I don't see a PR linked to #78 either.

**Comment by jimscarver** [comment]
the problem was still there in Group.rho, I fixed it to return only the group names.
