### ISSUE TITLE
TODO: Push more of the actions down into deployed contracts

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#131]
From #87

**Comment by Bill-Keuntje** [comment]
My understanding of this issue is that @jimscarver and @dckc differ on how much functionality should be in actions -- as opposed to rholang contracts. I think this relates to creating an rgov-api: #100

**Comment by dckc** [comment]
Thanks for opening this, but...

Until we have at least one specific case of what should be pushed down, this isn't actionable.

Maybe someone will think of one or two; then this should be reopened.

**Comment by Bill-Keuntje** [comment]
Agreed.
