### ISSUE TITLE
TODO: Working group (multi-sig actions)

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/rgov#132]
From #87

**Comment by Bill-Keuntje** [comment]
@dckc Does the current WorkingGroup.rho complete this issue?

**Comment by Bill-Kunj** [comment]
No response from @dckc, closing.

**Comment by dckc** [comment]
> Does the current WorkingGroup.rho complete this issue?

No, I don't think so. The title says actions, as in UI actions. WorkingGroup.rho alone doesn't do that.

(No need to reopen it until somebody is ready to take it on, I suppose.)
