### ISSUE TITLE
Web interface: Syntax highlighting

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#134]
Currently, there is indentation in the development interface.
Re-using the TextMate definitions for rholang would allow us to format/highlight rholang code as well.
https://github.com/tgrospic/rholang-sublime/blob/master/Syntaxes/Rholang.YAML-tmLanguage

**Comment by lingfan** [comment]
would allow us to  format  rholang code as well.
https://github.com/tgrospic/rholang-vscode

**Comment by Bill-Keuntje** [comment]
> would allow us to format rholang code as well.
> https://github.com/tgrospic/rholang-vscode

We are already using that for vscode. We need to do syntax highlighting in the web interface as well.

**Comment by Bill-Keuntje** [comment]
Replaced by #214
