### ISSUE TITLE
why keep a separate registry / map of Community by name?

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#14]
Why not just put each community into the rchain registry?

**Comment by dckc** [comment]
I'm testing code that creates a community; I have to keep changing the name of the community each time I run my tests. :-/

**Comment by dckc** [comment]
chatted with @jimscarver ... it's sort of by analogy to channels in discourse.

If I had not thrown away the admin capability, I could have reused the names.

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Six months old. Are the tests (https://github.com/rchain-community/rgov/issues/14#issuecomment-688534877) still failing?

**Comment by dckc** [comment]
I gather this was addressed, @jimscarver ? Would you please add a short note about how it was addressed?
