### ISSUE TITLE
Data Structures: treat ExprPar as NULL wrapper in test

### ISSUE THREAD

**Issue by w2vy** [rchain-community/rgov#146]
The following is deployed data of the inbox view with https://jsonformatter.curiousconcept.com/#

{'exprs': [{'expr': {'ExprPar': {'data': [{'ExprMap': {'data': {'URI': {'ExprUri': {'data': 'rho:id:g8utuu1dhow6xjfqa9xucriuezc6kjjbx5nn5898dm6mzid9nubzoe'}}}}}, {'ExprPar': {'data': [{'ExprList': {'data': [{'ExprString': {'data': 'issue'}}, {'ExprString': {'data': 'lunch'}}, {'ExprMap': {'data': {}}}]}}, {'ExprList': {'data': [{'ExprString': {'data': 'vote'}}, {'ExprString': {'data': 'lunch'}}, {'ExprMap': {'data': {}}}]}}]}}]}}, 'block': {'blockHash': '092a0d00b8cd35adc2832e572659385012aac77bbb0494bc624e97ed52221d1b', 'sender': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'seqNum': 45, 'sig': '30450221008d75e19ff64a2bdd09db8ea6641bddac0a6ae2cf228d0fc4150db582b288ec3e02200b4f618779993dbc27299bc38d361dfc6b0a6b654a2b8885d0ab51e1ac7b3a5d', 'sigAlgorithm': 'secp256k1', 'shardId': 'root', 'extraBytes': '', 'version': 1, 'timestamp': 1621787109138, 'headerExtraBytes': '', 'parentsHashList': ['4cda7f9a978bb1bf9ad75f0a6d5429d6c30ac9173d8dabdf09a491004698d591'], 'blockNumber': 45, 'preStateHash': 'e4375e73e81c41410c7a2a33c4b693ea9fe0f550cc7edf53822a545ee5711a15', 'postStateHash': 'c7da7aa5916418323d56570d1f75dbf798df6e271253988b4a9fc226637fcd6d', 'bodyExtraBytes': '', 'bonds': [{'validator': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'stake': 100000000000}], 'blockSize': '124772', 'deployCount': 1, 'faultTolerance': 1.0, 'justifications': [{'validator': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'latestBlockHash': '4cda7f9a978bb1bf9ad75f0a6d5429d6c30ac9173d8dabdf09a491004698d591'}]}}], 'length': 1}

The top level is:

exprs: expr and block
Inside expr we find Expar->data and inside that we have 
ExprMap and ExprPar

Inside the ExprMap we have the inbox URI
Inside the ExprPar is the issue and such, (oddly I do not see the voting choices.)
It could make it easier to parse if all entries were uniform type to this point
exprs.expr.Expar->data.ExprMap['URI']
exprs.expr.Expar->data.ExprMap['Voting']

This way when I read the deploy data I only need to know how to parse the thing I am looking for
I expect that JavaScript may see the same issues that I am seeing

**Comment by w2vy** [comment]
Here is an example of the data before the voter is added to the issue

{'exprs': [{'expr': {'ExprMap': {'data': {'URI': {'ExprUri': {'data': 'rho:id:3inryaqxaosrgx7awo3zc3otg7i3wx8aw4wzp888fhhpxtb44by4eh'}}}}}, 'block': {'blockHash': '893e7cda73f2fff249e79e4c33473671a198aa8aa552a7eba846218ca212df9d', 'sender': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'seqNum': 47, 'sig': '3044022025d2a26bfb8d452443b62289264e28fe47179bbf449a8ae1e35d4459aa9fe202022065cc4ae3e3f55e54bfb66eff16d668e7bb3aa26251ba91ffa428cfa2b97f4d96', 'sigAlgorithm': 'secp256k1', 'shardId': 'root', 'extraBytes': '', 'version': 1, 'timestamp': 1621797445592, 'headerExtraBytes': '', 'parentsHashList': ['3c2a4f545f5aa53e9e8f26ff5f5713bd2f1321feaeabfaf5c9daabf12af170d8'], 'blockNumber': 47, 'preStateHash': '0b663bc457d10f369c90c2fb66ebb39dfc9f3c857988007bfeaa106e96a2d51e', 'postStateHash': '376e4dcc45c842f39a3937cf3ac2345353ae44dd9572bae057b4b8db60705dec', 'bodyExtraBytes': '', 'bonds': [{'validator': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'stake': 100000000000}], 'blockSize': '124770', 'deployCount': 1, 'faultTolerance': 1.0, 'justifications': [{'validator': '04be064356846e36e485408df50b877dd99ba406d87208add4c92b3c7d4e4c663c2fbc6a1e6534c7e5c0aec00b26486fad1daf20079423b7c8ebffbbdff3682b58', 'latestBlockHash': '3c2a4f545f5aa53e9e8f26ff5f5713bd2f1321feaeabfaf5c9daabf12af170d8'}]}}], 'length': 1}

**Comment by Bill-Keuntje** [comment]
@w2vy @jimscarver 
does this have to do with #125?

**Comment by w2vy** [comment]
This one is more troubling.
In order to parse the deployed data returned by peekInbox the code needs to look in different places, so in short the data structure stored as deploy Data (ie deployId!(data)) changes based on when you look at it.

The second example was a created inbox (only containing it's URI)
The first example is later with an issue added

Will the parsing code new new rules once voting has started?

we should meet to discuss

**Comment by jimscarver** [comment]
this seems to be n rchain issue, not an rgov issue. Everywhere else we use data-at-name and your while your attempt to not use it is admerable I think it is out of scope for rgov. We need to be expedient. I suggest closing this and adding an rchain/rchain issue.

**Comment by w2vy** [comment]
Jim and I talked and it may beyond our control. I basically need to parse things treating ExprPar as a NULL wrapper, basically ignoring and skipping right over it

**Comment by Bill-Keuntje** [comment]
@w2vy Does this actually work?

**Comment by w2vy** [comment]
The python json does not seem to conform well to jq() so I have been parsing the protobuffer structures.

**Comment by jimscarver** [comment]
you tried https://pypi.org/project/jq/ ?
