### ISSUE TITLE
Publicize the bootstrap setup video

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#155]
@jimscarver where do we keep these for public consumption?

_Originally posted by @Bill-Keuntje in https://github.com/rchain-community/rgov/issues/109#issuecomment-846348402_

**Comment by David405** [comment]
@Bill-Keuntje @jimscarver  isn't the CoLab YouTube channel still functioning? That is a good place to save this I believe

**Comment by Bill-Keuntje** [comment]
Closed by https://youtu.be/P1jxxElpKX0
