### ISSUE TITLE
Community request doesn't supply return channel to inbox

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#16]
How does this work?

https://github.com/rchain-community/liquid-democracy/blob/60d7365f2776695babc9f0304e56dac80a4e34f4/Community.rho#L60

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Does the new @jimscarver work on Groups (#78) eliminate this issue?

**Comment by dckc** [comment]
`Community.rho` seems to be gone. I'm not sure if its contents got moved and might still have this issue, though.

**Comment by jimscarver** [comment]
Community is now group and the issue is no more
https://github.com/rchain-community/rgov/blob/5f578c899da1845143d4a2032e994ad383add36b/Group.rho#L142

joinGroup is now functional so I'll make a pull request to clean out the old Community stuff etc.
