### ISSUE TITLE
newInbox.rho no clear return information in DeployID

### ISSUE THREAD

**Issue by w2vy** [rchain-community/rgov#167]
newInbox sends a lot of debug info to the deployId with no clear case when it can fail; including creating a second inbox losing the first?

Makes it hard to unit test.
I can check the results with peekInbox, but that isn't a Unit Test

Can this be improved?

**Comment by Bill-Keuntje** [comment]
@w2vy New inbox has been completely reimplemented. Make sure you are on the latest code.

**Comment by Bill-Kunj** [comment]
@w2vy @jimscarver @David405 Is this a blocker for the rv2021 milestone?

**Comment by Bill-Kunj** [comment]
No forward progress on this, removing from rv2021 milestone (https://github.com/rchain-community/rgov/milestone/4).

**Comment by jimscarver** [comment]
this is no worse that the rest of the actions.
