### ISSUE TITLE
give emoji kudos

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/rgov#184]
From #86

**Comment by Bill-Kunj** [comment]
@dckc @jimscarver @David405 Would somebody please explain this issue to me?

**Comment by dckc** [comment]
I filled out the description of #86; I still don't know why this was split out.

**Comment by Bill-Kunj** [comment]
Closing because of https://github.com/rchain-community/rgov/issues/86#issuecomment-853370808
