### ISSUE TITLE
MasterURI.localhost.json is missing

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#185]
Did someone neglect to check it in?

https://github.com/rchain-community/rgov/blob/ad0fb531a9d151ab8b098e8ab6d6304cdcf22ce7/src/participate.js#L22

If it's the result of deploying something to a local chain, then it's not a design-time constant (as I explained May 18 https://github.com/rchain-community/rgov/issues/66#issuecomment-843683867 ) ; it should be read in at configuration time / runtime, through a file, environment variable, or some such.

@Bill-Keuntje `git blame` shows you committed this line, though the commit message was Revert "Add pyrchain testing...", which suggests we lost the actual history of who wrote it in a git mix-up.

**Comment by Bill-Keuntje** [comment]
MasterURI.localhost.json is the result of creating a localhost dev environment.
Should we create a (bogus) intermediary file? Will .gitignore still not present it in commit/push requests?

**Comment by dckc** [comment]
> Should we create a (bogus) intermediary file?

Yes, a configuration file would be appropriate. I don't see anything bogus about it.

> Will .gitignore still not present it in commit/push requests whe nit is changed because of localhost creation?

.gitignore should be updated with the name of the configuration file.

**Comment by dckc** [comment]
This seems to be why netlify builds are no longer working:

```
6:43:46 PM: $ npm run build:deploy
...
6:43:46 PM: > webpack
6:44:00 PM: Hash: dbb35c40a0f752a277d5
...
6:44:00 PM: ERROR in ./src/participate.js
6:44:00 PM: Module not found: Error: Can't resolve './MasterURI.localhost.json' in '/opt/build/repo/src'
 @ ./src/participate.js 21:0-62 39:15-31
6:44:00 PM:  @ ./src/index.js
```
 -- https://app.netlify.com/sites/rgov1/deploys/60b81790a6faf700086ee394#L72-L108

**Comment by dckc** [comment]
> Yes, a configuration file would be appropriate.

Note that a configuration file doesn't get `import`ed. `import` is for source code; i.e. design-time materials.

A configuration file would get read in at runtime.

(Another alternative would be an environment variable, as advocated by https://12factor.net/config )

**Comment by Bill-Keuntje** [comment]
Placeholder added.
