### ISSUE TITLE
allow resizing the textarea from any corner

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#201]
hmm... another dependency... please add an issue about this and let's discuss the risks / costs / benefits of it.

_Originally posted by @dckc in https://github.com/rchain-community/rgov/pull/190#discussion_r653121165_

**Comment by David405** [comment]
@Bill-Keuntje I didn't see a need to create a separate issue for this as I believe this isn't an important dependency....I only added it to allow users change the size of the text area from any direction, not necessarily mobile users but PC users, we could as well go with the default CSS way of resizing textarea.

**Comment by dckc** [comment]
In #190 I see
> Interact.js was used to make the rholang textarea resizable from all corners or part of the textarea, this helps a lot with the User Experience, I couldn't find a way to do to this with raw CSS or JS( I could only do that from one corner using CSS ), that was why I used an external library, if I figure that out with raw CSS or JS, then we could do away with interact.js.

The relevant issue that I was suggesting would be something like "make the rholang textarea resizable from all corners or part of the textarea" or "resizing the textarea is hard" and interactjs would be a proposed solution.

I'll edit the title and description here in a day or so unless I hear otherwise.

**Comment by David405** [comment]
@dckc oh now I see your point as stated in #204 but don't you think that if we have to create an issue for every problem encountered it might slow down the work?

FYI, I have problem doing this, I just want to gain clarity and improve my efficiency here

**Comment by dckc** [comment]
My experience is that if we _don't_ create an issue for every significant problem, it will slow down the work. This discussion is supporting evidence.

You have to go slow to go fast.

**Comment by David405** [comment]
@dckc Now I understand exactly your point.

Also, in my previous comment, I meant "I have NO problem doing this", just to be clear. I have edited it.

**Comment by dckc** [comment]
I don't see why allow resizing from any corner. I haven't seen other web sites do it. Github, in particular, doesn't do it.

**Comment by dckc** [comment]
looks like this proposal has been withdrawn: https://github.com/rchain-community/rgov/pull/190#issuecomment-867756704
