### ISSUE TITLE
Test: Fix test_voting.py

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#208]
I have updated the test_voting.py script which emulates the voting demo, but the branch does not have the inbox fix so the test fails. Can we approve the pull and then fix any issues in the independent file test_voting.py?

_Originally posted by @w2vy in https://github.com/rchain-community/rgov/issues/203#issuecomment-865491460_

**Comment by w2vy** [comment]
I was able to test and submit the required changes under issue 202 and the pull request that is in limbo
