### ISSUE TITLE
Dev interface second try (syntax highlight, visuals, button colors) 

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/rgov#214]
Replaces #134
Obsoletes #190 
branch: https://github.com/rchain-community/rgov/tree/214-dev-interface

**Comment by Bill-Keuntje** [comment]
Need answers to https://github.com/rchain-community/rgov/pull/190#issuecomment-871098487

**Comment by David405** [comment]
@Bill-Keuntje I also made a lot of efforts yesterday to reintroduce the ```oninput``` function to no avail, Like you said, I strongly agree that it has to do with the Prismjs handles the HTML elements, so right now we may have to seek for other solutions that would incorporate the ```<textarea>```.

This [solution](https://css-tricks.com/creating-an-editable-textarea-that-supports-syntax-highlighted-code/#the-solution) you posted has some important tricks we didn't include while the ```<textarea>``` existed, so I will test out some new changes while including the ```<textarea>```.

**Comment by Bill-Keuntje** [comment]
@David405 I've created the branch https://github.com/rchain-community/rgov/tree/214-dev-interface That has the working changes we've made. It also includes a ```<textarea>```. Let me know if I've missed something.
