### ISSUE TITLE
pyrgov upadates for new checkBalance.rho

### ISSUE THREAD

**Issue by w2vy** [rchain-community/rgov#215]
The modified rho file caused errors in pyrgov

**Comment by dckc** [comment]
Is this a bug? If so, what are the symptoms? What are the steps to reproduce it?

**Comment by Bill-Kunj** [comment]
@w2vy
You definitely know the testing framework better than anyone else. Can you put up a screenshot or log please?

**Comment by Bill-Kunj** [comment]
@dckc @jimscarver @w2vy 
I think I understand this better now.
We need to update ```CONTRIBUTING.md``` (or somewhere) so require changes of rholang actions to pass the integration tests before merge. Either 1) @w2vy needs to be on all rholang action reviews, or 2) integration tests need to be updated/passed before merge.

**Comment by w2vy** [comment]
In pyrgov.py it would fail on line 76 (raise an exception)
contract = string.Template(template).substitute(substitutions)

Because the rholang (template) would appear to have $var that was not offered a substitution.

This is fixed by PR 216
