### ISSUE TITLE
use cross-chain transfer voting example as stating point.

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/rgov#25]
https://github.com/rchain/rchain/blob/ce55a8adc349c05f62fb94fa028138ab93c71780/rholang/src/main/rholang/cross-shard.rho

The model of  mailboxes and ballots could be used with tickets / unforgeable names

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver
Can this issue be closed?

**Comment by dckc** [comment]
I can't speak for @jimscarver but for my purposes, yes, `WorkingGroup.rho` has the interesting parts of the cross-chain transfer voting stuff: voting using sealers and unsealers.
