### ISSUE TITLE
create and implement rholang contract that creates user inbox and cast votes 

### ISSUE THREAD

**Issue by David405** [rchain-community/rgov#259]
The basic code involves a combination of create inbox and cast votes contract done by @jimscarver, it just has to be refactored and implemented inside the voting interface

**Comment by Bill-Kunj** [comment]
@David405 If you believe this issue is unnecessary for rv2021, please remove the milestone requirement.....

**Comment by jimscarver** [comment]
this is done I think. @David405 ?
