### ISSUE TITLE
rv2021 hollywood demo 

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/rgov#266]
@jimscarver A demo will, of course, be necessary before October voting. Can you produce a starter "hollywood" script for the demo?

_Originally posted by @Bill-Kunj in https://github.com/rchain-community/rgov/issues/154#issuecomment-906895522_

**Comment by David405** [comment]
@Bill-Kunj seems like we have to do this ourselves

**Comment by Bill-Kunj** [comment]
No longer possible for September/October. Closing.
