### ISSUE TITLE
rename the repo to rgov?

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/rgov#41]
I suggest changing the liquid-democracy repo name to rgov since it is more encompassing than liquid and not necessarily liquid unless a group wants to be liquid. We call the app rgov in many places.  Are there any objections?

**Comment by dckc** [comment]
might as well.

I have a couple arguments against, but they're not critical:

1. I have a lot of habits around the name **liquid-democracy**... typing `liq` into my browser is enough to get me here.
2. I'm a little concerned that folks looking for it in the https://github.com/rchain-community list might miss it... for example, folks that learned about it from the dapp-ideas workshop.

**Comment by dckc** [comment]
Oh... another hesitation: **rgov** could imply this is *the* RChain governance project; i.e. that we owe a right of review to the whole community. While I welcome contributions from everybody, I'd like to reserve the right to make opinionated design choices. This is specifically about using [object capabilities](https://github.com/dckc/awesome-ocap) for cooperative work... including using ocaps in the JavaScript implementation!

It's probably better to spell that out in README / CONTRIBUTNG than to rely on the name alone, for that, though. **liquid-democracy** doesn't exactly say anything about ocaps.

**Comment by dckc** [comment]
with an updated README (#59), this seems like as good as any to rename the repo

**Comment by dckc** [comment]
done. agreed by JW, Bill, Tom
