### ISSUE TITLE
 URI_Directory error - NOT Error when using rnode-0.11.0-alpha

### ISSUE THREAD

**Issue by w2vy** [rchain-community/rgov#49]
[create-master-directory.log](https://github.com/rchain-community/liquid-democracy/files/6228409/create-master-directory.log)
I ran across this when using rnode 0.11, not sure if it is an issue for rgov or rnode(alpha)

./deploy-all: Propose finished.
./deploy-all: Generating javascript file [generated.rhoid.bootstrap.js]
./deploy-all: Generating json file [generated.rhoid.bootstrap.json]
./deploy-all: Generating directory creation rholang
Deploying generated.create-master-contract-directory.rho
Parsing error: Error in parsing term: 
coop.rchain.rholang.interpreter.errors$TopLevelFreeVariablesNotAllowedError: Top level free variables are not allowed: URI_Directory at 20:15.

URI_Directory is referenced on line 36 of bootstrap/master-contract-directory.sh

[create-master-directory.log](https://github.com/rchain-community/liquid-democracy/files/6228415/create-master-directory.log)

**Comment by Bill-Keuntje** [comment]
This error happens when the deploy of the rgov "*.rho" fails. It is more likely an error in an individual .rho file than an error in deploy-all or with URI_Directory. I know we put a fix in for something similar, but I can't track down the commit (it was wrapped up in reorganize-actions).
@w2vy Please offer instructions on how to install rnode 0.11.0-alpha so I can test.

**Comment by w2vy** [comment]
Go to [0.11-alpha2](https://github.com/rchain/rchain/releases/tag/v0.11.0-alpha.2) and download the [installer](https://github.com/rchain/rchain/releases/download/v0.11.0-alpha.2/rnode_0.11.0-alpha.2_all.deb)

apt install ./rnode_0.11.0-alpha.2_all.deb

and the build shard from scratch

**Comment by Bill-Keuntje** [comment]
@w2vy Is this fixed?

**Comment by jimscarver** [comment]
this turned out to not be related to rnode version.
