### ISSUE TITLE
locker using `deployerId` - no other crypto, no registry

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#5]
check out [Locker using `deployerID`](https://github.com/rchain-community/rv2020/tree/m3g/m3g#locker-using-deployerid)

The insight is: since `rho:rchain:deployerId` forms an unforgeable name, no other deployer can refer to it (unless you send it to them, and even then I'm not sure). Likewise compound names built with it. So `@[*deployer, "locker1", "put"]` is only available to one who holds the deployer key as well.

And the deployer can refer to it in any number of deploys without any registry lookups.

for reference:
 - [Locker.rho](https://github.com/rchain-community/rv2020/blob/m3g/m3g/Locker.rho)
 - [Locker_test1.rho](https://github.com/rchain-community/rv2020/blob/m3g/m3g/Locker_test1.rho) 

https://github.com/rchain-community/rv2020/commit/157eaf4a8f2357cb08c114ef70b88398cf8fe018

these are in the rv2020 on a branch just now; I'm not sure where to put them. I'm also not sure of the scope of this community repo, but I see some recent work on the Locker idea here.

cc @jimscarver

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Not sure what this issue is attempting to accomplish. Is it an attempt to merge https://github.com/rchain-community/rv2020/commit/157eaf4a8f2357cb08c114ef70b88398cf8fe018?

**Comment by jimscarver** [comment]
the deployid is now used instead of dan's original locker. It is a much better solution.
