### ISSUE TITLE
rgov1.netlify.app netlify deploy config outdated by reorganize-actions

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/rgov#54]
since we now have sepate files for each action the build command for netlify need to be updated when we do the merge to master.
```
npm run build; cp -pr src/actions dist/
```

**Comment by dckc** [comment]
something weird is going on:

![Screenshot from 2021-04-17 09-38-16](https://user-images.githubusercontent.com/150986/115116753-f9b50900-9f60-11eb-888c-ea05f3339e56.png)

**Comment by dckc** [comment]
I'm not sure how to proceed; this seems blocked on #80

**Comment by Bill-Keuntje** [comment]
Is netlify working correctly now?

**Comment by dckc** [comment]
yes.
