### ISSUE TITLE
deploy demo rchain network (rhobot)

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#55]
I gather that part of the preparation for a demo yesterday was setting up a network, but "everything broke" in some way.

@Bill-Keuntje says
> Current theory is we didn't have latest code.

**Comment by dckc** [comment]
@Bill-Keuntje to set up environment with @jimscarver 's advice.

wipe rhobot?
new VM?
@dckc is happy to spend a few bucks on a new droplet for a month or so.

**Comment by jimscarver** [comment]
robot will remain for people to play with. the separe demo system is just for official demos.

**Comment by dckc** [comment]
What's the next step on the separate demo system?

Or did you mean to close this, @jimscarver ?

**Comment by jimscarver** [comment]
rhobot is done, demo still needs https fixed

**Comment by dckc** [comment]
> rhobot is done, demo still needs https fixed

not for the demo, though. We rehearsed without https; adding https at this point adds unacceptable risk.

In any case, I don't see how https is relevant to this issue, which is about an rchain network. The front-end issue is #56.

**Comment by Bill-Keuntje** [comment]
Done
