### ISSUE TITLE
Standardize storage of "ReadcapURI"

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#66]
Currently, ReadcapURI should not be checked in to source control. However, the file is updated whenever a bootstrap process is performed, regardless of platform (rhobot, demo, localhost). This leads to easy commit mistakes. A better mechanism of storing the various ReadcapURIs for each platform is needed that does not conflict with source control processes.

**Comment by jimscarver** [comment]
what do you mean? I think we we should have separate files for each network

**Comment by dckc** [comment]
The master directory read cap URI is clearly not a design-time constant, so it shouldn't be checked in.

The 12factor conventions are aging a bit but they still work. By that convention, such config info goes in environment variables.

**Comment by dckc** [comment]
Why is this assigned to me? What am I expected to do?

**Comment by jimscarver** [comment]
it is checked in with the testnet uri to make it work on netlify. If you have a better way, go for it @dckc   It should never be committed with a localhost uri. It is rather awkward.

**Comment by jimscarver** [comment]
I'd like your input on how to handle ReadcapURIs for the various systems that are generated by bootstrap.

I think a separate file for each network could work with localhost.ReadcapURI in .gitignore

**Comment by Bill-Keuntje** [comment]
My thought was always to have a separate file for each network.

**Comment by jimscarver** [comment]
I merged master recently and now see ```

        modified:   ReadcapURI.json
        modified:   src/MasterURI.localhost.json
```
so it seems this work is in progress...

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver 
Is this issue properly addressed by the creation of `rho:rchain:rgov`? #126

**Comment by dckc** [comment]
I doubt it. I don't really understand this issue, but `rho:rchain:rgov` doesn't seem like a good use of community resources.

**Comment by dckc** [comment]
The way I see it, the bottom line is that ReadcapURI is not a design-time constant. It's a function of the state of whatever rchain network the app connects to. I don't see any sense in pretending otherwise.

**Comment by Bill-Keuntje** [comment]
The thought here is to make ```rho:rchain:rgov``` the design-time constant and eliminate the need for ReadcapURI (or any other uri file for that matter). Without this, the source control confusion is already apparent: https://github.com/rchain-community/rgov/issues/66#issuecomment-822003857

The work to implement ```rho:rchain:rgov``` is not significant other than the study required to do insertSigned() and the modification of bootstrap to perform the required deploy/propose

**Comment by dckc** [comment]
insertSigned won't make validator nodes understand rho:rchain:rgov

**Comment by Bill-Keuntje** [comment]
After considerable discussion with @tgrospic, ```rho:rchain:rgov``` is not tenable. We still need to standardize the way we store network URIs.
