### ISSUE TITLE
New inbox should run using the master directory uri of the selected network

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#67]
In the current implementation, "newinbox" can be performed on a system other than the one running the interface. Of course, this fails since "newinbox" requires the ReadcapURI in order to work. When selecting "newinbox", it should be impossible to select an alternative Network in the dropdown.

**Comment by Bill-Keuntje** [comment]
@jimscarver 
Is this issue equivalant to issue #115?

**Comment by jimscarver** [comment]
No, this is about using the correct uri for the selected network.

**Comment by Bill-Keuntje** [comment]
This involves participate using the src/MasterURI.<network>.json files instead of ReadcapURI.json file.

**Comment by Bill-Keuntje** [comment]
Closed by PR #173
