### ISSUE TITLE
delete liquid-democracy branch after demo

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#71]

**Comment by dckc** [comment]
why create an issue? Why not just delete the branch? oh yeah... we wanted to keep it 'till after the demo, just in case

**Comment by Bill-Keuntje** [comment]
@dckc, @jimscarver, @w2vy 
I guess we should delete this branch now?

**Comment by dckc** [comment]
I see from https://github.com/rchain-community/rgov/branches/all that somebody already deleted it.
