### ISSUE TITLE
bootstrap: Fix/Document voter-insertion.rho

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#73]
voter-insertion creates the "Roll" entry in the master dictionary, but there is no explanation of what this is.
Also, "Roll" seems like a bad name.

**Comment by jimscarver** [comment]
https://en.wikipedia.org/wiki/Electoral_roll

the roll will be the membership of a group so this will be listGroupMembers

**Comment by Bill-Keuntje** [comment]
fixed by #107
