### ISSUE TITLE
does directory.rho implement the PetNames ocap pattern?

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#8]
here's hoping I find time to review from this angle.

https://github.com/dckc/awesome-ocap/wiki/PetNames

_p.s. This is meant as an issue in the liquid democracy work. @jimscarver , your latest work on directory.rho seems to be here in rho-bot, so I'm raising the issue here._

**Comment by jimscarver** [comment]
directory.rho is a key-value store not necessarily about users. It allows separate object capabilities to be created (granted) for each key which makes it useful for user directories with a self modification capability. A pet names directory could be created using it.

**Comment by Bill-Keuntje** [comment]
Since we've stabilized Directory.rho and done the demo, is this still an issue?

**Comment by dckc** [comment]
In our demo we used registry URIs. That certainly doesn't address this issue.

**Comment by Bill-Keuntje** [comment]
> In our demo we used registry URIs. That certainly doesn't address this issue.

#126 helps to address the issue of using URIs, but https://github.com/dckc/awesome-ocap/wiki/PetNames is not my area of expertise, so I leave resolution to @dckc

**Comment by jimscarver** [comment]
petnames are not implemented but everyone has a personal directory so there can be a personal rover, a group rover and a global rgov rover.

**Comment by dckc** [comment]
So as stated, the issue is addressed: no, it doesn't.

I'm still interested in PetNames, but I can make a separate issue if I get any more clear about it.
