### ISSUE TITLE
show avatars for members; give emoji kudos

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#86]
one member could give kudos to another, using emoji reactions as in discord

The kudos might actually be negotiable tokens.

suggested by @leithaus

**Comment by Bill-Keuntje** [comment]
Closed by #183 and #184

**Comment by dckc** [comment]
#183 and #184 aren't done, so I don't see how this is addressed.

Also, I'm not sure #183 and #184 are useful by themselves.

**Comment by dckc** [comment]
OTOH, this issue was a result of a suggestion from @leithaus , and I haven't heard any interest from him for some time.

I don't feel strongly about keeping it open on my account.

**Comment by Bill-Kunj** [comment]
> OTOH, this issue was a result of a suggestion from @leithaus , and I haven't heard any interest from him for some time.
> 
> I don't feel strongly about keeping it open on my account.

Agreed.
