### ISSUE TITLE
bootstrap: lookupURI is broken

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#92]
lookupURI was written to rely on our actions not having a match statement.
Since we've added match statements to actions, the script no longer works.

**Comment by Bill-Keuntje** [comment]
Update: I'm not sure that lookupURI is relevant anymore, but it is a nice tool when debugging low-level issues.

**Comment by jimscarver** [comment]
lookupURI is no broken anymore but should use explore, not deploy.

I have made the update in https://github.com/rchain-community/rgov/pull/139
