### ISSUE TITLE
bootstrap: Add "adam", "beth", and "chip" REV addresses with REV balance

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#93]
The private keys for adam, beth, and chip are in pk.adam, pk.beth, and pk.chip
Each account should be given one million REV to start.

**Comment by Bill-Keuntje** [comment]
After discussion with @w2vy, this is fixed by #127 
No account/REV will be allocated into a localhost rgov database.

**Comment by w2vy** [comment]
Should we have a different set of private keys for each possible network?
Like a directory for each network name:
localnet, demonet, rhobot, testnet, mainnet

Also the mainnet could be empty so no shared private keys there...

Where should these directories reside?

**Comment by Bill-Keuntje** [comment]
I agree, and the python testing effort is a great way to insure that this works.
