### ISSUE TITLE
Rename Inbox.rho

### ISSUE THREAD

**Issue by Bill-Keuntje** [rchain-community/rgov#99]
Inbox.rho does not represent a person's 'Inbox'. It represents a personal 'Locker' or 'Mailbox', which can be created under many identifiers (not just 'inbox').
The filename and code should reflect this.

The fix isn't simply a search/replace in the file. The MasterDirectoryAdmin should be double-checked for accuracy as well as src/actions/*.rho for the new semantics.

**Comment by dckc** [comment]
> Inbox.rho does not represent a person's 'Inbox'.

no? I believe it does.

> It represents a personal 'Locker' or 'Mailbox', which can be created under many identifiers (not just 'inbox').

How does that disqualify it from being an Inbox?

> The filename and code should reflect this.

The code is fine as it is.

**Comment by Bill-Keuntje** [comment]
This would be true if Inbox.rho is only for rgov.
Fact is, the locker is *always* referred to as "inbox" within rgov but the concept -- and code -- is more general, therefore deserving of a more general (reussable) semantic.

**Comment by dckc** [comment]
Argument by assertion doesn't get us far. I can make the opposite claims: the code is not more general and the name is nearly ideal; certainly not bad enough to offset the cost of changing it.

**Comment by jimscarver** [comment]
I agree the name may be misleading but the inbox is only part of what is in the locker and it is not actually mail that it is generally used for. I am not convinced there is a better name proposed.

The agile thing to do at this point is nothing.
